/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-06-14 15:33:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.FinalProject;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class spot1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Festival Travel</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Big+Shoulders+Stencil+Display&family=Caveat:wght@700&family=Nunito:ital,wght@1,700&family=Varela+Round&display=swap');\r\n");
      out.write("body{\r\n");
      out.write("background:powderblue;\r\n");
      out.write("padding:0px 40px;\r\n");
      out.write("}\r\n");
      out.write("#logo{\r\n");
      out.write("margin:10px 0px 10px 0px;\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("display:inline-block;\r\n");
      out.write("color:#303974;\r\n");
      out.write("text-shadow:3px 3px 4px #60a3bc;\r\n");
      out.write("font-size:55px;\r\n");
      out.write("font-family: 'Caveat', cursive;\r\n");
      out.write("line-height:35px;\r\n");
      out.write("}\r\n");
      out.write("#topmenu{\r\n");
      out.write("width:470px;\r\n");
      out.write("height:40px;\r\n");
      out.write("margin-top:70px;\r\n");
      out.write("float:right;\r\n");
      out.write("}\r\n");
      out.write("#topmenu ul li{\r\n");
      out.write("list-style:none;\r\n");
      out.write("color:white;\r\n");
      out.write("float:left;\r\n");
      out.write("text-align:center;\r\n");
      out.write("height:40px;\r\n");
      out.write("vertical-align:center;\r\n");
      out.write("line-height:40px;\r\n");
      out.write("margin-right:10px;\r\n");
      out.write("}\r\n");
      out.write("#topmenu .menu{\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("color:white;\r\n");
      out.write("display:block;\r\n");
      out.write("width:120px;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("font-size:25px;\r\n");
      out.write("}\r\n");
      out.write("#topmenu .menu:hover{\r\n");
      out.write("text-decoration:underline;\r\n");
      out.write("}\r\n");
      out.write("div{\r\n");
      out.write("text-align:center;\r\n");
      out.write("position:relative;\r\n");
      out.write("width:500px;\r\n");
      out.write("margin:auto;\r\n");
      out.write("}\r\n");
      out.write("#map1{\r\n");
      out.write("width:515px;\r\n");
      out.write("margin-top:30px;\r\n");
      out.write("z-index:-3;\r\n");
      out.write("}\r\n");
      out.write("#map2{\r\n");
      out.write("width:139px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:55px;\r\n");
      out.write("left:75px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map2:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map3{\r\n");
      out.write("width:50px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:118px;\r\n");
      out.write("left:113px;\r\n");
      out.write("z-index:1;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map3:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map4{\r\n");
      out.write("width:205px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:42px;\r\n");
      out.write("left:154px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map4:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map5{\r\n");
      out.write("width:137px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:192px;\r\n");
      out.write("left:64px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map5:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map6{\r\n");
      out.write("width:120px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:170px;\r\n");
      out.write("left:163px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map6:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map7{\r\n");
      out.write("width:163px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:185px;\r\n");
      out.write("left:216px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map7:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map8{\r\n");
      out.write("width:139px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:292px;\r\n");
      out.write("left:84px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map8:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map9{\r\n");
      out.write("width:158px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:369px;\r\n");
      out.write("left:55px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map9:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map10{\r\n");
      out.write("width:179px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:319px;\r\n");
      out.write("left:189px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map10:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map11{\r\n");
      out.write("width:58px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:195px;\r\n");
      out.write("left:430px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map11:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map12{\r\n");
      out.write("width:82px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:530px;\r\n");
      out.write("left:56px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map12:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#map13{\r\n");
      out.write("width:26px;\r\n");
      out.write("position:absolute;\r\n");
      out.write("top:230px;\r\n");
      out.write("left:149px;\r\n");
      out.write("opacity:0;\r\n");
      out.write("}\r\n");
      out.write("#map13:hover{\r\n");
      out.write("opacity:1;\r\n");
      out.write("}\r\n");
      out.write("#date{\r\n");
      out.write("position:fixed;\r\n");
      out.write("float:left;\r\n");
      out.write("bottom:5px;\r\n");
      out.write("color:grey;\r\n");
      out.write("font-size:13px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
request.setCharacterEncoding("utf-8"); 
      out.write('\r');
      out.write('\n');
      Javabean.RootBean rt = null;
      synchronized (session) {
        rt = (Javabean.RootBean) _jspx_page_context.getAttribute("rt", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (rt == null){
          rt = new Javabean.RootBean();
          _jspx_page_context.setAttribute("rt", rt, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("rt"), request);
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("<img src=\"logo.png\" id=\"logo\" width=80>\r\n");
      out.write("<h1>Festival<br>Travel</h1>\r\n");
      out.write("<nav id=\"topmenu\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li><a class=\"menu\" href=\"festival1.jsp\">FESTIVAL</a></li>\r\n");
      out.write("<li>|</li>\r\n");
      out.write("<li><a class=\"menu\" href=\"spot1.jsp\" style=\"color:midnightblue;text-decoration:underline;\">SPOT</a></li>\r\n");
      out.write("<li>|</li>\r\n");
      out.write("<li><a class=\"menu\" href=\"root.jsp\">ROOT</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("</header>\r\n");
      out.write("<div>\r\n");
      out.write("<img src=\"map1.png\" id=\"map1\">\r\n");
      out.write("<a href=\"spot2.jsp?map=경기도\"><img src=\"map2.png\" id=\"map2\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=서울특별시\"><img src=\"map3.png\" id=\"map3\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=강원도\"><img src=\"map4.png\" id=\"map4\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=충청남도\"><img src=\"map5.png\" id=\"map5\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=충청북도\"><img src=\"map6.png\" id=\"map6\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=경상북도\"><img src=\"map7.png\" id=\"map7\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=전라북도\"><img src=\"map8.png\" id=\"map8\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=전라남도\"><img src=\"map9.png\" id=\"map9\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=경상남도\"><img src=\"map10.png\" id=\"map10\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=울릉도\"><img src=\"map11.png\" id=\"map11\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=제주특별자치도\"><img src=\"map12.png\" id=\"map12\"></a>\r\n");
      out.write("<a href=\"spot2.jsp?map=세종특별자치시\"><img src=\"map13.png\" id=\"map13\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("<p id=\"date\">관광지 데이터 업데이트 날짜 : 2021-06-07</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
